#!/bin/bash
source "$(dirname "$0")/../common.sh"

nswipe thames
mkcourse $COURSE/10
$SSH_CP "bash -s" <<'REMOTE'
set -euo pipefail
rm -rf /course6/10
mkdir -p /course6/10
REMOTE

webserver thames vault 1 vault-v1
client thames alpha
client thames beta

kubectl apply -f - >/dev/null <<'EOF'
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: thames
spec:
  selector:
    app: vault
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
EOF

waitdeploy thames vault
waitdeploy thames alpha
waitdeploy thames beta

# Pod IPs are handed out at schedule time, so the question cannot hard-code
# them. Discover them now and write them into the file the task reads, which
# makes the exercise deterministic for this run of setup.sh.
alpha_ip=$(kubectl -n thames get pod -l app=alpha -o jsonpath='{.items[0].status.podIP}')
beta_ip=$(kubectl -n thames get pod -l app=beta  -o jsonpath='{.items[0].status.podIP}')
[[ -n "$alpha_ip" && -n "$beta_ip" ]] || { echo "could not read Pod IPs" >&2; exit 1; }
pod_net="$(echo "$alpha_ip" | cut -d. -f1-2).0.0/16"

$SSH_CP "cat > /course6/10/peers.txt" <<EOF
# thames — network inventory, generated by setup.sh
# These are live addresses. If you re-create the Pods, re-run setup.sh.

pod-network-cidr:  $pod_net
alpha-pod-ip:      $alpha_ip
beta-pod-ip:       $beta_ip

# The quarantined host, as a single-address CIDR:
quarantined:       $beta_ip/32
EOF

echo "READY q10 — thames: vault Service, clients alpha+beta, addresses written to /course6/10/peers.txt (both clients can reach vault)"
