apiVersion: v1
kind: Namespace
metadata:
  name: personal-website
  labels:
    purpose: application-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: grindtrack
  labels:
    purpose: application-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    purpose: cluster-infrastructure
