apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    purpose: application-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    purpose: cluster-infrastructure
