# GENERATED BY TERRAFORM — do not edit by hand (see terraform/outputs.tf).
# Regenerate with: cd terraform && terraform apply
all:
  vars:
    ansible_user: deploy
    ansible_ssh_private_key_file: ~/.ssh/hetzner_k8s
  children:
    control_plane:
      hosts:
        ${cluster_name}-cp-1:
          ansible_host: ${cp_public_ip}
          private_ip: ${cp_private_ip}
    workers:
      hosts:
        ${cluster_name}-worker-1:
          ansible_host: ${worker_public_ip}
          private_ip: ${worker_private_ip}
